channels = [
    {enabled=true,  inverted=false, coupling="DC", impedance="50 ohm", range="±1 V"},
    {enabled=true,  inverted=false, coupling="DC", impedance="50 ohm", range="±1 V"},
    #{enabled=false, inverted=false, coupling="DC", impedance="50 ohm", range="±2 V"},
    #{enabled=false, inverted=false, coupling="DC", impedance="50 ohm", range="±2 V"},
]


[sample_clock]
source = "Internal"
rate = "100 MS/s" 
# source = "External"
# rate = "80.37 MS/s" # measure external clock precisely (note the wavelength-dependence)
edge = "Rising"


[trigger]
source = "External"
slope = "Rising"
level = "1.0 V"
#external_range = "TTL"
external_range = "±5 V"
external_coupling = "DC"