channels = [
    {enabled=true,  inverted=false, coupling="DC", impedance="50 ohm", range="±2 V"},
    {enabled=true,  inverted=false, coupling="DC", impedance="50 ohm", range="±2 V"},
    {enabled=false, inverted=false, coupling="DC", impedance="50 ohm", range="±2 V"},
    {enabled=false, inverted=false, coupling="DC", impedance="50 ohm", range="±2 V"},
]


[sample_clock]
# source = "Internal clock"
# rate = "100 MS/s"
source = "Fast external clock"
rate = "80.3 MS/s" # measure external clock precisely (note the wavelength-dependence)
# 80.28 MHz @ 1045 nm
edge = "Rising"


[trigger]
source = "External"
slope = "Positive"
level = "0 V"
external_range = "TTL"
external_coupling = "DC"