# strip acquisition
x_range = {min = "1 mm", max = "61 mm"}
y_range = {min = "10 mm", max = "70 mm"}
strip_overlap = 0.05

# line camera acquisition
line_width = "60 mm"
pixel_size = "40 um"
integration_time = "0.4 ms"
line_period = "0.5 ms"
lines_per_buffer = 250