# stitched area
x_range = {min = "35 mm", max = "60 mm"}
y_range = {min = "35 mm", max = "60 mm"}
strip_overlap = 0.01

# raster scan
bidirectional_scanning = true
line_width = "1.5 mm"
pixel_size = "1.0 Î¼m"
fill_fraction = 0.90
lines_per_buffer = 1500
