
[laser_scanning_optics]
relay_magnification = 4
objective_focal_length = "20 mm"


[camera_optics]
magnification = 0.25 # not calibrated yet


[detectors]

[detectors.0]
type = "ecu1_pmt"

[detectors.1]
type = "ecu1_pmt"


[digitizer] # Include settings that are required for start up / will NOT change
type = "Alazar" # could add: model number, serial number to distinguish cards in multicard setups


[stage]
type = "BBD202"
# Nominal speed, anything else?
[stage.x_config]
axis = "x"
position_limits = {min = "1 mm", max = "109 mm"}

[stage.y_config]
axis = "y"
position_limits = {min = "1 mm", max = "74 mm"}


# [objective_scanner]
# type = TBD


[encoders] # via NI PCIe-6321
type = "linear_encoders_via_ni"

[encoders.x_config]
signal_a_channel = "/Dev1/RTSI4"
signal_b_channel = "/Dev1/RTSI3"
sample_clock_channel = "/Dev1/PFI0"
trigger_channel = "/Dev1/PFI3" # output trigger for linearization
distance_per_pulse = "200 nm"

[encoders.y_config]
signal_a_channel = "/Dev1/RTSI5"
signal_b_channel = "/Dev1/RTSI6"
sample_clock_channel = "/Dev1/PFI0"
distance_per_pulse = "200 nm"


[fast_raster_scanner]
type = "ecu1_resonant_scanner"
axis = "y"
angle_limits = {min = "-13.0 deg", max = "13.0 deg"}
frequency = "7910 Hz"
# ECU1 has an internal DAC to control amplitude, so no AO channel is used
com_port = 4
enable_channel = "" # remove

[slow_raster_scanner]
type = "slow_galvo_scanner_via_ni"
axis = "x"
external_line_clock_channel = "/Dev1/PFI0" # fast axis sync signal (in)
frame_clock_channel = "/Dev1/PFI4" # generated frame clock (out)
analog_control_channel = "Dev1/ao1" # axis waveform analog out
angle_limits = {min = "-20.0 deg", max = "20.0 deg"}
analog_control_range = {min = "-10 V", max = "10 V"}


[frame_grabber] # NI PCIe-1429
type = "ni_frame_grabber"
device_name = "img0"


[line_scan_camera]
type = "uniiqa_plus_color"
axis = "y"
pixel_size = "5 Î¼m"


[illuminator]
type = "led_via_ni"
enable_channel = "Dev1/port0/line6"
