
[optics] # TODO make multiple optics?
relay_magnification = 4
objective_focal_length = "20 mm"


[digitizer] # Include settings that are required for start up / will NOT change
type = "Alazar" # could add: model number, serial number to distinguish cards in multicard setups


[stage]
type = "BBD202"
# Nominal speed, anything else?
[stage.x_config]
axis = "x"
position_limits = {min = "1 mm", max = "109 mm"}

[stage.y_config]
axis = "y"
position_limits = {min = "1 mm", max = "74 mm"}


# [objective_scanner]
# type = "trinamic_objective_z_scanner"
# axis = "z"
# com_port = 5
# step_angle = "1.8 deg"
# travel_per_rev = "100 Î¼m"


[encoders]
type = "linear_encoders_via_ni"

[encoders.x_config]
counter_name = "Dev1/ctr0"
signal_a_channel = "/Dev1/RTSI4"
signal_b_channel = "/Dev1/RTSI3"
sample_clock_channel = "/Dev1/PFI0"
trigger_channel = "/Dev1/PFI3" # output trigger for linearization
distance_per_pulse = "200 nm"

[encoders.y_config]
counter_name = "Dev1/ctr1"
signal_a_channel = "/Dev1/RTSI5"
signal_b_channel = "/Dev1/RTSI6"
sample_clock_channel = "/Dev1/PFI0"
distance_per_pulse = "200 nm"


[fast_raster_scanner]
type = "ecu1_resonant_scanner"
axis = "y"
angle_limits = {min = "-13.0 deg", max = "13.0 deg"}
frequency = "7910 Hz"
#analog_control_range = {min = "0 V", max = "5 V"}
com_port = 4
#amplitude_control_channel = "Dev1/ao2"
enable_channel = "" # or None

[slow_raster_scanner]
type = "galvo_slow_raster_scanner_via_ni"
axis = "y"
line_clock_channel = "/Dev1/PFI0" # fast axis sync signal (in)
frame_clock_channel = "Dev1/port0/line7" # generated frame clock (out)
trigger_channel = "/Dev1/PFI4" # waveform trigger (this will just be frame_clock_channel routed back in)
control_channel = "Dev1/ao1" # axis waveform analog out
angle_limits = {min = "-20.0 deg", max = "20.0 deg"}
analog_control_range = {min = "-10 V", max = "10 V"}


[frame_grabber]
type = "ni_frame_grabber"
device_name = "img0"


[line_scan_camera]
type = "uniiqa_plus_color"
axis = "y"


[illuminator]
type = "led_via_ni"
enable_channel = "Dev1/port0/line6"
