bidirectional_scanning = true
line_width = "3 mm"
pixel_size = "2 μm"
#pixel_height = "1 μm" #(optional)
fill_fraction = 0.9
x_range = {min = "30 mm", max = "60 mm"}
y_range = {min = "25 mm", max = "55 mm"}
strip_overlap = 0.1
lines_per_buffer = 512
buffers_allocated = 8
nchannels = 2 # must match digitizer profile (shouldn't it just pull from digitizer profile?)
digitizer_profile = "default"