line_width = "2 cm"
pixel_size = "40 μm"
#pixel_height = "1 μm" # (optional)
x_range = {min = "2 mm", max = "98 mm"}
y_range = {min = "35 mm", max = "55 mm"}
integration_time = "0.4 ms"
integration_duty_cycle = 0.95
