line_width = "2 cm"
pixel_size = "20 μm"
#pixel_height = "1 μm" # (optional)
x_range = {min = "20 mm", max = "90 mm"}
y_range = {min = "25 mm", max = "45 mm"}
integration_time = "0.2 ms"
integration_duty_cycle = 0.9
