channels = [
    {enabled=true,  inverted=false, coupling="dc", impedance="1 MΩ", range="±1 V", channel="Dev1/ai0"},
    {enabled=false, inverted=false, coupling="dc", impedance="1 MΩ", range="±1 V", channel="Dev1/ai1"},
    {enabled=false, inverted=false, coupling="dc", impedance="1 MΩ", range="±1 V", channel="Dev1/ai2"},
    {enabled=false, inverted=false, coupling="dc", impedance="1 MΩ", range="±1 V", channel="Dev1/ai3"}
]


[sample_clock]
source = "internal"
rate = "1.25 MS/s"
edge = "rising"


[trigger]
source = "internal"
slope = "rising"