line_width = "6 cm"
pixel_size = "40 μm"
#pixel_height = "1 μm" # (optional)
x_range = {min = "20 mm", max = "80 mm"}
y_range = {min = "5 mm", max = "65 mm"}
integration_time = "0.4 ms"
integration_duty_cycle = 0.75
