bidirectional_scanning = true
line_width = "1.0 mm"
frame_height = "1.0 mm"
pixel_size = "1.0 Î¼m"
fill_fraction = 0.99
buffers_per_acquisition = 'Inf'  
buffers_allocated = 4
digitizer_profile = "default"
flyback_periods = 64 # Number of cycles of the fast scanner for slow scanner flyback
